spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  security:
    oauth2:
      client:
        registration:
          cognito:
            clientId: ${cognito.client.id}
            clientSecret: ${cognito.client.secret}
            scope: openid
            redirect-uri: http://localhost:8080/login/oauth2/code/cognito
            clientName: ${cognito.client.name}
        provider:
          cognito:
            issuerUri: https://cognito-idp.eu-central-1.amazonaws.com/${cognito.user-pool.id}
            #userNameAttribute: username

cloud:
  aws:
    region:
      static: eu-central-1
    credentials:
      instanceProfile: true

aws:
  profile: ${PROFILE}

logging:
  level:
    org:
      springframework:
        security: DEBUG

s3:
  bucket:
    images: kotsial-images-central
    audios: kotsial-mpegs-central
